
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: lab-dev
    ports:
      - "8888:8888"          # JupyterLab
    environment:
      JUPYTER_TOKEN: lab     # token rapido per entrare
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./work:/home/jovyan/work
    depends_on:
      - mongo
      - neo4j
      - kafka
    networks:
      - lab-net

  mongo:
    image: mongo:7
    container_name: lab-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - lab-net

  neo4j:
    image: neo4j:5.25.1-community
    container_name: lab-neo4j
    ports:
      - "7474:7474"   # HTTP UI
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=512M
    volumes:
      - neo4jdata:/data
      - neo4jlogs:/logs
      - neo4jplugins:/plugins
    networks:
      - lab-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.8-1-ubi8
    container_name: lab-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - lab-net

  kafka:
    image: confluentinc/cp-kafka:7.6.8
    container_name: lab-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # due listener: esterno (localhost:9092) e interno per gli altri container (kafka:29092)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - lab-net


volumes:
  mongodata:
  neo4jdata:
  neo4jlogs:
  neo4jplugins:

networks:
  lab-net:
    driver: bridge
